# Generated by Django 4.2.3 on 2023-09-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
