# Generated by Django 4.2.3 on 2023-09-08 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='description',
            new_name='descripcion',
        ),
    ]
